CREATE TABLE IF NOT EXISTS alert_rule_templates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(64) DEFAULT '',
    name VARCHAR(256) NOT NULL,
    description TEXT,
    datasource_type VARCHAR(32) DEFAULT '',
    expression TEXT NOT NULL,
    for_duration VARCHAR(32) DEFAULT '0s',
    severity VARCHAR(32) NOT NULL,
    labels JSON,
    annotations JSON,
    group_name VARCHAR(128) DEFAULT '',
    eval_interval INT DEFAULT 60,
    is_builtin TINYINT(1) DEFAULT 0,
    usage_count INT DEFAULT 0,
    created_by BIGINT UNSIGNED DEFAULT 0,
    updated_by BIGINT UNSIGNED DEFAULT 0,
    nodata_enabled TINYINT(1) DEFAULT 0,
    nodata_duration VARCHAR(32) DEFAULT '5m',
    ack_sla_minutes INT DEFAULT 0,
    created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_category (category),
    INDEX idx_severity (severity),
    INDEX idx_datasource_type (datasource_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
